version: "3"
services:
  postgres:
    image: postgres:alpine
    command: postgres -c 'max_connections=250'
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-spokedev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-spoke}
      POSTGRES_USER: ${DB_USER:-spoke}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
volumes:
  postgres:
    external: false
  redis:
    external: false
