version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: spokedev
      POSTGRES_PASSWORD: spoke
      POSTGRES_USER: spoke
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  app:
    build:
      context: .
      args:
        SPOKE_VERSION: 1.4.1
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://spoke:spoke@postgres:5432/spokedev
      REDIS_URL: redis://redis:6379
    image: spoke
    ports:
      - 3000:3000
    volumes:
      - ./.env:/Spoke/.env
volumes:
  postgres:
    external: false
  redis:
    external: false
