version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: spokedev
      POSTGRES_PASSWORD: spoke
      POSTGRES_USER: spoke
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
  spoke:
    image: spokeapp/spoke
    build:
      context: .
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://spoke:spoke@postgres:5432/spokedev
      REDIS_URL: redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - ./.env:/Spoke/.env
volumes:
  postgres:
    external: false
  redis:
    external: false
